include:
  - path: compose.${DB_DEFAULT:-postgresql}.yml
    env_file: .env
  - path: compose.base.yml
    env_file: 
    - .env
    - .env.redis
    - .env.openSearch
  - path: compose.openSearch.yml
    env_file: 
     - .env  
     - .env.openSearch
  - path: compose.cache.yml
    env_file: 
     - .env
     - .env.redis
#  - path: compose.certbot.yml

      
 



