x-api: &default-api
  image: openimis-be-main:${BE_TAG:-latest}
  environment:
    - DB_DEFAULT=${DB_DEFAULT:-postgresql}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - SECRET_KEY=${SECRET_KEY}
    - SITE_ROOT=api
    - SITE_URL=${DOMAIN}
    - CELERY_BROKER_URL=amqp://rabbitmq
    - MODE=${MODE:-Prod}
    - HOSTS=${HOSTS}
    - CACHE_BACKEND=${CACHE_BACKEND}
    - CACHE_URL=${CACHE_URL}
    - CACHE_OPTIONS=${CACHE_OPTIONS}
    - OPENSEARCH_ADMIN=${OPENSEARCH_ADMIN}
    - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
    - TOKEN_KOBO = ${TOKEN_KOBO}
    - IBB_API_USERNAME=${IBB_API_USERNAME}
    - IBB_API_PASSWORD=${IBB_API_PASSWORD}
    - IBB_PARTNER_PIN=${IBB_PARTNER_PIN}
    - LUMICASH_API_KEY=${LUMICASH_API_KEY}
    - LUMICASH_AUTH_USERNAME=${LUMICASH_AUTH_USERNAME}
    - LUMICASH_AUTH_PASSWORD=${LUMICASH_AUTH_PASSWORD}

  volumes:
    - photos:/photos
  depends_on:
    db:
      condition: service_healthy
  networks:
    openimis-net:
  restart: always

services:
  frontend:
    image: openimis-fe-main:${FE_TAG:-latest}
    restart: always
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${DOMAIN}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
      - OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN}
    networks:
      openimis-net:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # comment the following line if you are using your own gateway
      - ./conf/nginx:/conf/
  backend:
    <<: *default-api
    command: start      
  worker:
    <<: *default-api
    command: worker
    deploy:
      mode: replicated
      replicas: ${WORKER_REPLICAS:-3}
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
networks:
  openimis-net:
    name: "${PROJECT_NAME:-openimis}-net"
volumes:
  database:
  photos:
