#version: '3.7'
services:

  opensearch:
    image: opensearchproject/opensearch:latest
    env_file:
      - ".env.openSearch"
    environment:
      - "discovery.type=${DISCOVERY_TYPE:-single-node}"
      - "cluster.name=${CLUSTER_NAME:-my_opensearch_local}"
      - "http.port=${OPEN_SEARCH_HTTP_PORT:-9200}"
      - "plugins.security.ssl.http.enabled=${SLL_HTTP_ENABLED:-false}"
      - "plugins.security.disabled=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - "opensearch-data1:/usr/share/opensearch/data"
    networks:
      openimis-net:

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    container_name: ${PROJECT_NAME:-openimis}-opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS:-http://opensearch:9200}
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - SERVER_BASEPATH=/opensearch
      - SERVER_REWRITEBASEPATH=true
    volumes:
      - "./conf/opensearch/opensearch.yml:/usr/share/opensearch-dashboards/config/opensearch.yml"
    networks:
      openimis-net:

volumes:
  opensearch-data1:

# networks:
#   openimis-net:
#     name: "${PROJECT_NAME:-openimis}-net"
#     external: true

